### ISSUE TITLE
0.1+0.2!=0.3

### ISSUE THREAD

**Issue by haxer-max** [haxer-max/javascript_calculator#2]
when we try 0.1 +0.2 it outputs 0.3000..01 something. It will be great if it is fixed

**Comment by naomi-lgbt** [comment]
This has to do with a floating point issue. I can take a look at this if you'd like.

**Comment by haxer-max** [comment]
@nhcarrigan  ya, I thought one way of rounding the digits or something without affecting small decimal multi, but it was getting complex,
you can take this issue, it will be very helpful

**Comment by charchitmangal** [comment]
Hello! i want to Work this Issue

**Comment by haxer-max** [comment]
@nhcarrigan  now 0.1*0.2 is giving answer as 0. This is too much rounding

**Comment by haxer-max** [comment]
@charchithere ya go on

**Comment by naomi-lgbt** [comment]
AHH good to know. Hadn't thought of that. 
I can adjust the code. How many significant figures do you want?

**Comment by haxer-max** [comment]
@nhcarrigan  4 after decimal digits if >1, else 4 significant figures

**Comment by naomi-lgbt** [comment]
Sure thing 👍🏻

**Comment by naomi-lgbt** [comment]
I am just about off for the night. I will pick back up tomorrow, but if @charchithere finds a better approach first I will not be offended 🙂

**Comment by piyushverma001** [comment]
I have figured out the issue. I am fixing it if its not yet fixed

**Comment by haxer-max** [comment]
@piyushverma001  yes the issue is open

**Comment by piyushverma001** [comment]
give me a second the issue is solved i am making a PR.

**Comment by piyushverma001** [comment]
i made a PR kindly review it.

**Comment by piyushverma001** [comment]
@haxer-max did you check it out if it solves your problem or not??

**Comment by haxer-max** [comment]
@piyushverma001  great, just can you remove the unnecessary 0s from the ending

**Comment by haxer-max** [comment]
Solved by @piyushverma001
